#!/bin/bash

echo "Make sure you sun this script as sudo!"
echo "Creating Symbolic links in the bin..."

## Change this to your bin!! ##
BIN='${HOME}/bin'

mkdir $BIN

WILDLINES=$PWD
echo "Creating symbolic links to current folder," $WILDLINES

# Make all the files executable
sudo chmod +x ./*

# Create symbolic links
ln -sf $WILDLINES/checklines.py      $BIN/checklines
ln -sf $WILDLINES/quickplot.py       $BIN/quickplot
ln -sf $WILDLINES/read_kurucz.py     $BIN/read_kurucz
ln -sf $WILDLINES/read_TOSS.py       $BIN/read_TOSS
ln -sf $WILDLINES/read_uky.py        $BIN/read_uky
ln -sf $WILDLINES/read_VALD.py       $BIN/read_VALD
ln -sf $WILDLINES/reportlines.py     $BIN/reportlines
ln -sf $WILDLINES/wildlines.py       $BIN/wildlines
ln -sf $WILDLINES/plot_balmer.py     $BIN/plot_balmer

# Check for python dependancies
python -c 'import numpy'
if [ $? = 1 ]; then
    sudo -H pip install numpy
else
    echo "Numpy is installed!"
fi

python -c 'import matplotlib'
if [ $? = 1 ]; then
    sudo -H pip install matplotlib
else
    echo "Matplotlib is installed!"
fi

python -c 'import os'
if [ $? = 1 ]; then
    sudo -H pip install os
else
    echo "os is installed!"
fi

python -c 'import signal'
if [ $? = 1 ]; then
    sudo -H pip install signal
else
    echo "signal is installed!"
fi

python -c 'import subprocess'
if [ $? = 1 ]; then
    sudo -H pip install subprocess
else
    echo "subprocess is installed!"
fi

python -c 'import fnmatch'
if [ $? = 1 ]; then
    sudo -H pip install fnmatch
else
    echo "fnmatch is installed!"
fi

python -c 'import time'
if [ $? = 1 ]; then
    sudo -H pip install time
else
    echo "time is installed!"
fi

python -c 'import Tkinter'
if [ $? = 0 ]; then
    echo -e "\e[7m\e[5mYou don't have Tkinter installed! Please go get it!"
    echo -e "http://www.greenteapress.com/thinkpython/swampy/install.html\e[0m"
else
    echo "Tkinter is installed!"
fi

python -c 'import ScrolledText'
if [ $? = 1 ]; then
    sudo -H pip install 
else
    echo "ScrolledText is installed!"
fi

python -c 'import cycler'
if [ $? = 1 ]; then
    sudo -H pip install 
else
    echo "cycler is installed!"
fi


# Print a bit of help for the user.
echo ""
echo "If you got no error messages, you should now have the follwoing commands:"
echo "- read_kurucz"
echo "- read_uky"
echo "- read_TOSS"
echo "- read_VALD"
echo "--> These take the outputs from the relevant websites (see comments of each script for details) and converts to .lte format"
echo ""
echo "quickplot   - Reads a spectrum file, or any file separated into columns, and plots a given section of it in a publication-style plot"
echo "plot_balmer - Reads a spectrum, and generates plots of it's balmer lines. Can write to screen or a file"
echo "reportlines - Reads and summarises a .lte file"
